### ISSUE TITLE
Error launching docker image: "Config is not defined"

### ISSUE THREAD

**Issue by adr-arroyo** [Engineering-Research-and-Development/iotagent-opcua#20]
Hello,

I am launching the agent in a docker-compose file along with some other FIWARE components and I am getting this error when the OPC UA agent launches:

```
iotage_1          | time=2019-06-04T11:16:53.891Z | lvl=INFO | corr=n/a | trans=n/a | op=Index.Initialize | comp=iotAgent-OPCUA | srv=n/a | subsrv=n/a | msg=----------------------------------------------------
iotage_1          | time=2019-06-04T11:16:53.893Z | lvl=INFO | corr=n/a | trans=n/a | op=Index.Initialize | comp=iotAgent-OPCUA | srv=n/a | subsrv=n/a | msg=endpointUrl         =  opc.tcp://<ipaddr>:<port>
iotage_1          | time=2019-06-04T11:16:53.893Z | lvl=INFO | corr=n/a | trans=n/a | op=Index.Initialize | comp=iotAgent-OPCUA | srv=n/a | subsrv=n/a | msg=securityMode        =  NONE
iotage_1          | time=2019-06-04T11:16:53.895Z | lvl=INFO | corr=n/a | trans=n/a | op=Index.Initialize | comp=iotAgent-OPCUA | srv=n/a | subsrv=n/a | msg=securityPolicy      =  0
iotage_1          | time=2019-06-04T11:16:53.897Z | lvl=INFO | corr=n/a | trans=n/a | op=Index.Initialize | comp=iotAgent-OPCUA | srv=n/a | subsrv=n/a | msg=timeout             =  -1
iotage_1          | {"op":"IoTAgentNGSI.DomainControl","time":"2019-06-04T11:16:53.901Z","lvl":"ERROR","msg":"{ ReferenceError: config is not defined\n    
at Object.run (/opt/iotagent-opcua/iot_agent_modules/run/run.js:95:36)\n    
at /opt/iotagent-opcua/index.js:89:21\n    
at ChildProcess.exithandler (child_process.js:288:5)\n   
at emitTwo (events.js:126:13)\n    
at ChildProcess.emit (events.js:214:7)\n     
at maybeClose (internal/child_process.js:915:16)\n     
at Socket.stream.socket.on (internal/child_process.js:336:11)\n     
at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n     
at Pipe._handle.close [as _onclose] (net.js:561:12)\n  domain: \n   Domain {\n     domain: null,\n 
_events: { error: [Function: domainErrorHandler] },\n     _eventsCount: 1,\n     
_maxListeners: undefined,\n     members: [],\n      
start: 1559647009724,\n     trans: '6cab4c02-8950-4627-aa7d-84517463d3a3',\n     corr: '6cab4c02-8950-4627-aa7d-84517463d3a3',\n     op: 'IoTAgentNGSI.DeviceService' },\n  domainThrown: true }"}
```

My docker-compose configuration for the agent is:

```
  iotage:
    hostname: iotage
    image: rdlabengpa/opcuaage:latest
    networks:
      fiwareNetwork:
        aliases:
          - iotagent-opcua
    ports:
      - "4001:4001"
      - "4081:8080"
    depends_on:
      - mongodb
    volumes:
      - ./AGECONF:/opt/iotagent-opcua/conf
```

And the config.properties file looks like:

```
namespace-ignore=2
context-broker-host=orion
context-broker-port=1026
server-base-root=/
server-port=4001
device-registry-type=memory
mongodb-host=mongodb
mongodb-port=27017
mongodb-db=iotagent
mongodb-retries=5
mongodb-retry-time=5
fiware-service=<service>
fiware-service-path=<service-path>
provider-url=http://iotage:4001
device-registration-duration=P1M
endpoint=opc.tcp://<ipaddr>:<port>
log-level=DEBUG

#DATATYPE MAPPING OPCUA --> NGSI
OPC-datatype-Number=Number
OPC-datatype-Decimal128=Number
OPC-datatype-Double=Number
OPC-datatype-Float=Number
OPC-datatype-Integer=Integer
OPC-datatype-UInteger=Integer
OPC-datatype-String=Text
OPC-datatype-ByteString=Text
#END DATATYPE MAPPING OPCUA --> NGSI

#SESSION PARAMETERS
requestedPublishingInterval=500
requestedLifetimeCount=1000
requestedMaxKeepAliveCount=5
maxNotificationsPerPublish=10
publishingEnabled=true
priority=10

#SERVER CERT E AUTH
securityMode=NONE
securityPolicy=
userName=
password=

#Administration Services
api-port=4081
#End Administration Services

#POLL COMMANDS SETTINGS
polling=false
polling-commands-timer=30000
pollingDaemonFrequency=20000
pollingExpiration=200000
#END POLL COMMANDS SETTINGS

#AGENT ID
agent-id=iotagent-opcua


samplingInterval=1
queueSize=10
discardOldest=True
```

Actually the last parameters (samplingInterval, queueSize, discardOldest) are there because I was getting an error the first time I launched the agent saying that those were null, so I put them in the configuration file with some "random" values.

Are those errors due to not setting the fiware_path and fiware_service_path parameters? I am not sending any data to the agent yet.

Or because of the endpoint parameter? Actually this last parameter I do not know what it refers to, can I get some advice on what to put here?

Thanks and BR!

**Comment by gabrieledeluca** [comment]
Hello,
the OPC UA Agent has a built-in Mapping Tool in order to create the (automatic) mapping between OPC UA nodes and NGSI entities/attributes. So, you should have an OPC UA Server (the _endpoint_ parameter of _configuration.properties_ file). Moreover, you need Orion Context Broker for communicating with the Northbound side (_context-broker-host_ and _context-broker-port_ parameters).

You could create the mapping file manually (or edit the Mapping Tool output) but you'll have other errors if you don't have both, the OPC UA Server and the OCB up and running.

BTW, we have implemented an OPC UA Server useful for testing purposes: [https://github.com/Engineering-Research-and-Development/opc-ua-car-server](https://github.com/Engineering-Research-and-Development/opc-ua-car-server)

Regarding monitoring parameters, I've added them also on the README page, thanks!

Please feel free to contact me if you need any further information.

Best Regards,
Gabriele

**Comment by adr-arroyo** [comment]
Dear Gabriele,

Thanks for the fast response. I modified my configuration according to your answer. Now my files look like:

config.properties:

```
namespace-ignore=2
context-broker-host=orion
context-broker-port=1026
server-base-root=/
server-port=4001
device-registry-type=memory
mongodb-host=mongodb
mongodb-port=27017
mongodb-db=iotagentopc
mongodb-retries=5
mongodb-retry-time=5
fiware-service=UA
fiware-service-path=CarServer
provider-url=http://iotage:4001
device-registration-duration=P1M
endpoint=opc.tcp://aieng:5001
log-level=DEBUG

#DATATYPE MAPPING OPCUA --> NGSI
OPC-datatype-Number=Number
OPC-datatype-Decimal128=Number
OPC-datatype-Double=Number
OPC-datatype-Float=Number
OPC-datatype-Integer=Integer
OPC-datatype-UInteger=Integer
OPC-datatype-String=Text
OPC-datatype-ByteString=Text
#END DATATYPE MAPPING OPCUA --> NGSI

#SESSION PARAMETERS
requestedPublishingInterval=500
requestedLifetimeCount=1000
requestedMaxKeepAliveCount=5
maxNotificationsPerPublish=10
publishingEnabled=true
priority=10

#SERVER CERT E AUTH
securityMode=NONE
securityPolicy=
userName=
password=

#Administration Services
api-port=4081
#End Administration Services

#POLL COMMANDS SETTINGS
polling=false
polling-commands-timer=30000
pollingDaemonFrequency=20000
pollingExpiration=200000
#END POLL COMMANDS SETTINGS

#AGENT ID
agent-id=iotagent-opcua


#MONITORING PARAMETERS
samplingInterval= 0
queueSize= 10000
discardOldest= false
```

I have the OPC UA Car testing server running in opc.tcp://aieng:5001/UA/CarServer.

Additionally, my docker compose file for orion & the agent (I have more components but I do not place them all here):

```
  mongodb:
    image: mongo:3.2
    ports:
      - "27017:27017"
    expose:
      - "27017"
    command: --nojournal
    networks:
      - fiwareNetwork
    volumes:
      - "./data/db:/data/db"

  orion:
    image: fiware/orion:2.1.0
    ports:
      - "1026:1026"
    command:
      -dbhost mongodb
      -corsOrigin __ALL
      -logLevel DEBUG
    networks:
      - fiwareNetwork
    depends_on:
      - mongodb

  iotage:
    hostname: iotage
    image: rdlabengpa/opcuaage:latest
    networks:
      fiwareNetwork:
        aliases:
          - iotagent-opcua
    ports:
      - "4001:4001"
      - "4081:8080"
    depends_on:
      - mongodb
    volumes:
      - ./AGECONF:/opt/iotagent-opcua/conf
```

Despite this, I still have the same error in the docker-compose. Any clues on what could be happening??

BR,

Adrian
