### ISSUE TITLE
"Executed expiring daemon" from IoTAgentNGSI.ContextServer

### ISSUE THREAD

**Issue by chumvan** [Engineering-Research-and-Development/iotagent-opcua#61]
I am working with the IoT Agent for OPCUA with the following setting:
The server is OPC UA Prosys Server Simulation

`AGECONF/config.json`:
```
{
  "logLevel" : "DEBUG",
  "contextBroker" : {
    "host" : "orion",
    "port" : 1026
  },
  "server" : {
    "port" : 4001,
    "baseRoot" : "/"
  },
  "deviceRegistry" : {
    "type" : "memory"
  },
  "mongodb" : {
    "host" : "iotmongo",
    "port" : "27017",
    "db" : "iotagent",
    "retries" : 5,
    "retryTime" : 5
  },
  "types" : {
    "7:Simulation" : {
      "service" : "opcua_car",
      "subservice" : "/demo",
      "active" : [ {
        "name" : "7:Counter",
        "type" : "Number"
      }, {
        "name" : "7:Random",
        "type" : "Number"
      }, {
        "name" : "7:Sawtooth",
        "type" : "Number"
      }, {
        "name" : "7:Sinusoid",
        "type" : "Number"
      }, {
        "name" : "7:Square",
        "type" : "Number"
      }, {
        "name" : "7:Triangle",
        "type" : "Number"
      } ],
      "lazy" : [ ],
      "commands" : [ ]
    }
  },
  "browseServerOptions" : null,
  "service" : "opcua_car",
  "subservice" : "/demo",
  "providerUrl" : "http://iotage:4001",
  "pollingExpiration" : "200000",
  "pollingDaemonFrequency" : "20000",
  "deviceRegistrationDuration" : "P1M",
  "defaultType" : null,
  "contexts" : [ {
    "id" : "age01_7:Simulation",
    "type" : "7:Simulation",
    "service" : "opcua_car",
    "subservice" : "/demo",
    "polling" : false,
    "mappings" : [ {
      "ocb_id" : "7:Counter",
      "opcua_id" : "ns=7;i=1001",
      "object_id" : null,
      "inputArguments" : [ ]
    }, {
      "ocb_id" : "7:Random",
      "opcua_id" : "ns=7;i=1002",
      "object_id" : null,
      "inputArguments" : [ ]
    }, {
      "ocb_id" : "7:Sawtooth",
      "opcua_id" : "ns=7;i=1003",
      "object_id" : null,
      "inputArguments" : [ ]
    }, {
      "ocb_id" : "7:Sinusoid",
      "opcua_id" : "ns=7;i=1004",
      "object_id" : null,
      "inputArguments" : [ ]
    }, {
      "ocb_id" : "7:Square",
      "opcua_id" : "ns=7;i=1005",
      "object_id" : null,
      "inputArguments" : [ ]
    }, {
      "ocb_id" : "7:Triangle",
      "opcua_id" : "ns=7;i=1006",
      "object_id" : null,
      "inputArguments" : [ ]
    } ]
  } ],
  "contextSubscriptions" : [ ]
}
```
`opcua-postgres.yml` as a `docker-compose` file:
```
version: "3"
#secrets:
#   age_idm_auth:
#      file: age_idm_auth.txt

services:
  iotage:
    hostname: iotage
    image: iotagent4fiware/iotagent-opcua:1.3.4
    networks:
      - hostnet
      - iotnet
    ports:
      - "${AGENT_SERVER_PORT}:${AGENT_SERVER_PORT}"
      - "4081:8080"
    extra_hosts:
      - "iotcarsrv:192.168.50.167"
      - "HP:192.168.50.167"
    depends_on:
      - iotmongo
      - orion
    volumes:
      - ./AGECONF:/opt/iotagent-opcua/conf
      - ./certificates:/opt/iotagent-opcua/certificates
    command: /usr/bin/tail -f /var/log/lastlog

  iotmongo:
    hostname: iotmongo
    image: mongo:3.4
    networks:
      - iotnet
    volumes:
      - iotmongo_data:/data/db
      - iotmongo_conf:/data/configdb

  ################ OCB ################

  orion:
    hostname: orion
    image: fiware/orion:latest
    networks:
      - hostnet
      - ocbnet
    ports:
      - "${ORION_PORT}:${ORION_PORT}"
    depends_on:
      - orion_mongo
    #command: -dbhost mongo
    entrypoint: /usr/bin/contextBroker -fg -multiservice -statCounters -dbhost mongo -logForHumans -logLevel DEBUG -t 255

  orion_mongo:
    hostname: orion_mongo
    image: mongo:3.4
    networks:
      ocbnet:
        aliases:
          - mongo
    volumes:
      - orion_mongo_data:/data/db
      - orion_mongo_conf:/data/configdb
    command: --nojournal

  ############### CYGNUS ###############

  cygnus:
    image: fiware/cygnus-ngsi:${CYGNUS_VERSION}
    hostname: cygnus
    container_name: fiware-cygnus
    networks:
      - hostnet
    depends_on:
      - postgres-db
    expose:
      - "${CYGNUS_POSTGRESQL_SERVICE_PORT}" # 5055
      - "${CYGNUS_API_PORT}" # 5080
    ports:
      - "${CYGNUS_POSTGRESQL_SERVICE_PORT}:${CYGNUS_POSTGRESQL_SERVICE_PORT}"
      - "${CYGNUS_API_PORT}:${CYGNUS_API_PORT}"
    environment:
      - "CYGNUS_POSTGRESQL_SERVICE_PORT=${CYGNUS_POSTGRESQL_SERVICE_PORT}"      
      - "CYGNUS_POSTGRESQL_HOST=postgres-db" # Hostname of the PostgreSQL server used to persist historical contex
      - "CYGNUS_POSTGRESQL_PORT=${POSTGRES_DB_PORT}" # Port that the PostgreSQL server uses to listen to commands
      - "CYGNUS_POSTGRESQL_DATABASE=${POSTGRES_DB}"
      - "CYGNUS_POSTGRESQL_USER=postgres" # Username for the PostgreSQL database user
      - "CYGNUS_POSTGRESQL_PASS=password" # Password for the PostgreSQL database user
      - "CYGNUS_POSTGRESQL_ENABLE_CACHE=true" # Switch to enable caching within the PostgreSQL configuration
      - "CYGNUS_SERVICE_PORT=${CYGNUS_POSTGRESQL_SERVICE_PORT}" # Notification Port that Cygnus listens when subcr
      - "CYGNUS_API_PORT=${CYGNUS_API_PORT}" # Port that Cygnus listens on for operational reasons
      - "CYGNUS_LOG_LEVEL=DEBUG" # The logging level for Cygnus


  postgres-db:
    image: postgres
    hostname: postgres-db
    expose:
      - "${POSTGRES_DB_PORT}"
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
    networks:
      - hostnet
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=${POSTGRES_DB}"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  iotmongo_data:
  iotmongo_conf:
  orion_mongo_data:
  orion_mongo_conf:
  postgres-db:

networks:
  hostnet:
  iotnet:
  ocbnet:
```
The certificates were created and put in both OPCUA server and client (Fiware OPCUA agent).
I got this error, which was not shown ever during last implementation.

![image](https://user-images.githubusercontent.com/33626152/139041610-14f058da-474e-4754-b7a7-863f39c9a435.png)

The error message is ambiguous for me as I don't know which daemon it is referring to.
I have check the `dockerd` with `sudo systemctl status dockerd` which showed active
![image](https://user-images.githubusercontent.com/33626152/139047534-e4ee39d0-29e9-4afd-8696-ce2bb0c7657e.png)

After about 5 mins the agent showed this

![image](https://user-images.githubusercontent.com/33626152/139041704-fcefd427-6773-4d20-a80a-1dafb248d292.png)
