### ISSUE TITLE
Two connections opc ua

### ISSUE THREAD

**Issue by IsabelManiega** [Engineering-Research-and-Development/iotagent-opcua#66]
Hi! 
I would like to know, how is the implementation for the two connection on iotagent.
I try two endpoints on config.properties
for example:   
```
## SOUTHBOUND CONFIGURATION (OPC UA)
namespace-ignore=0,3,7
endpoint=opc.tcp://server:4840; opc.tcp://server:5840; 
```

The nodeID is 2 in both cases.
I used the config.json.MULTIPLE_DEVICES file, for example, and the docker-compose.yml in iotagent I put:
```
iotage:
      hostname: iotage
      image: iotagent4fiware/iotagent-opcua:1.3.4
      networks:
          - fiware_default
      ports:
          - "4001:4001"
          - "4081:8080"
      extra_hosts:
          - "server:10.150.10.110"
      depends_on:
          - mongo-db
          - orion
      volumes:
          - ./AGECONF:/opt/iotagent-opcua/conf
      command: /usr/bin/tail -f /var/log/lastlog
```
How do I do it?
Are there more necessary changes or I need another agent in this case?
